### ISSUE TITLE
TO-DO LIST 만들기

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#11]
## 🌈 Success criteria

1. TO-DO-LIST를 작성한다.

## 👷 To-do

- [ ] 할일 1 : 데이터셋 선정, 주제 선정
- [ ] 할일 2 : 데이터 전처리
- [ ] 할일 3 : 유사도 측정
- [ ] 할일 4 : content_based filtering
- [ ] 할일 5 : collaborative filtering
- [ ] 할일 6 : 두 필터링 방식을 혼합하여 hybrid filtering 구현
- [ ] 할일 7 : streamlit상에 출력
- [ ] 할일 8 : 추천 시스템 초기 단계에서  사용자 정보 input받는 알고리즘 구현
- [ ] 할일 9 : 추천 시스템 출력시 편의시설 옵션 필터링해주는 체크박스 알고리즘 구현
- [ ] 할일 10 : 시연영상 제작
- [ ] 할일 11 : README파일 작성
- [ ] 할일 12 : PPT 제작
