### ISSUE TITLE
유사도 구하기 - Word2Vec

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#15]
## 🌈 Success criteria

1. Word2Vec 를 이용해서 한글로 구성된 단어들의 유사성을 구해보자

## 👷 To-do

- [x] 할일 1 gensim 설치하기
- [ ] 할일 2 형태소 분리를 위해 konlpy 설치하기
- [x] 할일 3 분리된 data를 대상으로 Word2Vec 으로 유사도 구하기

## 🧶 Review

- konlpy를 설치 실패;; java 설치, jpype1 설치, 가상환경 만들기, 커널 추가하기 등등 시도
- 형태소를 수동으로 분리하여 유사도 측정을 진행했지만, 만족스러운 결과가 나오지 않음
