### ISSUE TITLE
유사도 구하기 - FastText

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#18]
## 🌈 Success criteria

1. FastText를 통해 유사도를 계산한다.

## 👷 To-do

- [x] 할일 1 : FastText 한국어 사전학습 모델 다운로드
- [x] 할일 2 : 사용할 단어들에 대한 정보만 남긴 커스텀 모델 제작
- [x] 할일 3 : 대/중/소분류별 unique값에 대해 상호 유사도 계산
