### ISSUE TITLE
데이터 전처리

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#3]
## 🌈 Success criteria

1. 분석을 시작하기 전에 필요한 데이터 전처리 과정을 수행한다.
2. 관광지 데이터와 방문기록 데이터에 대해 각각 전처리과정을 거친 후 평점을 기준으로 pivot-table을 만든다.
## 👷 To-do

**관광지 데이터**
- [x] 할일 1 : 제주 지역에 해당하는 데이터만 남기고 다른 행을 삭제한다.
- [x] 할일 2 : 분석에 사용하지 않을 column을 삭제한다
- [x] 할일 3 : 무료주차여부, 유료주차여부 컬럼을 합쳐서 주차가능여부 컬럼 만들기
- [x] 할일 4 : 필요시 범주형 데이터를 숫자형 type으로 인코딩한다.
- [x] 할일 5 : 시설명 id column을 생성한다.
- [x] 할일 6 : 훈련에 넣을 column과 훈련에는 넣지 않지만 남겨둘 column을 구분한다.

**방문기록 데이터**
- [x] 할일 1 : TRAVEL_ID, TRAVELER_ID column을 기준으로 필요한 데이터들을 합친 dataframe을 생성한다.
- [x] 할일 2 : 분석에 사용하지 않을 column을 삭제한다.
- [x] 할일 3 : 결측치를 처리한다.
- [x] 할일 4 : 주거지, 공항 등 관광지로 보기 어려운 데이터들을 삭제한다.

**데이터 병합**
- [x] 할일 1 : FCLTY_NM column을 기준으로 두 dataframe을 병합한다.
- [x] 할일 2 : DGSTFN column을 기준으로 pivot-table을 만든다.
