### ISSUE TITLE
content_based filtering

### ISSUE THREAD

**Issue by minmaru99** [pladata-encore/DA36_mini2_Jeju_for_All#30]
## 🌈 Success criteria

1. 이전에 구한 카테고리별 유사성을 기반으로 contents-based filtering 을 시켜보자

## 👷 To-do

- [x] 할일 1 train_df를 불러오기
- [x] 할일 2 원하는 카테고리를 입력받는다(input)
- [x] 할일 3 입력한 카테고리를 ct_sim(유사도 데이터프레임)에서 찾은 후 유사도를 기준으로 내림차순 정렬한다
- [x] 할일 4 train_df에서 입력한 카테고리에 해당하는 fctly_nm을 반환하여 리스트에 저장한다.
- [x] 할일 5 중복값을을 제외하고 상위 20개의 fclty_nm을 반환한다.

## 🧶 Review

```
selected_category = input("원하는 장소의 분류를 선택하세요: ")

sim_scores = ct_sim[selected_category].sort_values(ascending=False)
sim_scores = sim_scores[1:].index  # 자기 자신 제외
recommend_fclty = []

for category in sim_scores:
    facilities = train_df[train_df['CTGRY_THREE_NM'] == category]['FCLTY_NM']  

    for fclty in facilities:
        if fclty not in recommend_fclty:  
            recommend_fclty.append(fclty)
    if len(recommend_fclty) >= 20: 
        break

print(f"---------🏝️{selected_category}🏝️에 해당하는 추천 장소---------🏝️")
for fclty in recommend_fclty[:20]:  # 20개만 출력
    print(fclty)
```
