### ISSUE TITLE
추가적인 전처리 작업

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#33]
## 🌈 Success criteria

1. 분석 진행중에 추가로 필요해진 전처리 작업을 수행한다.

## 👷 To-do

- [ ] 할일 1 : 여행 스타일 중 훈련에 이용하기에 적절하지 않은 컬럼을 삭제한다.
- [ ] 할일 2 : 이전에 삭제한 컬럼 중 훈련에 이용할만한 컬럼이 있는지 테스트한다.
- [ ] 할일 3 : csv파일에 수정사항을 적용하고, 그에 맞게 각 코드도 고친다.
