### ISSUE TITLE
사용자 행동 데이터 생성

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#4]
## 🌈 Success criteria

1. 데이터셋에 있는 장소들에 대한 개별 사용자의 방문 데이터를 생성한다.

## 👷 To-do

- [ ] 할일 1 : 사용자id, 성별, 연령대, 방문일 등의 정보를 포함한다.
- [ ] 할일 2 : 사용자들이 여러 장소에 충분히 방문한 기록이 남게끔 충분한 양(5000개 이상?)의 데이터를 생성한다.
- [ ] 할일 3 : 추천하기에 의미있는 데이터가 나올 수 있도록 방문장소와 나머지 데이터 사이에 어떠한 경향성이 생기도록 한다.
