### ISSUE TITLE
정규화된 유사도, 평점에 가중치를 부여해서 최종 순위 반환하기

### ISSUE THREAD

**Issue by minmaru99** [pladata-encore/DA36_mini2_Jeju_for_All#50]
## 🌈 Success criteria

1. 상세설명
2.

## 👷 To-do

- [x] 예측 평점을 0~1점으로 정규화
- [x] 카테고리 유사도 데이터프레임과 정규화된 예측 평점 데이터프레임 병합 후 가중치 부여
- [x] 부여된 가중치로 합산하여 나온 값으로 최종 순위 도출
