### ISSUE TITLE
데이터셋에서 사용할 클래스 확정

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#80]
## 🌈 Success criteria

1. 데이터셋을 살펴보고 모델 훈련 및 평가에 사용할 클래스들을 확정한다.
- '대형 폐기물 처리'라는 주제에 어울리는 품목
- 1000개 이상의 이미지 파일을 확보할 수 있는 품목

## 👷 To-do

- [ ] 할일 1 : 디렉토리별로 이미지 파일이 5장씩 있는데, 훈련시 5개의 이미지가 같은 객체인 걸 인식시킨 채로 훈련할 방법이 있는지 확인
- [ ] 할일 2 : 사용하기로 한 4개의 클래스 외에 추가할만한 다른 클래스(전자제품, 종이류 등 더 큰 범주 or 다른 가구 종류)가 있는지 확인
- [ ] 할일 3 : 개별 디렉토리에 있는 파일들 하나의 디렉토리로 꺼내서 합쳐야 하는지 확인 / 합쳐야 한다면 어떻게 합칠지 방법 찾아보기

## 🧶 Review
**사용할 클래스 :** 밥상, 서랍장, 소파, 수납장, 의자(총 5개 클래스)

- 서랍장과 수납장이 너무 비슷하게 생기지는 않았는지 확인해봐야 할 듯 -> 서랍장 데이터셋 폐기
- 클래스별 약 1000장의 이미지를 추출하여 모델 훈련 예정
