### ISSUE TITLE
프로토타입 모델 훈련

### ISSUE THREAD

**Issue by srogsrogi** [pladata-encore/DA36_mini2_Jeju_for_All#82]
## 🌈 Success criteria

1. 모델 훈련을 시작하기 전에 프로토타입 모델을 만들어 훈련시켜보고 결과를 바탕으로 실제 훈련시킬 모델을 설계한다.

## 👷 To-do

- [x] 할일 1 : 구글드라이브에 클래스별 40개의 폴더(200개 파일)를 업로드한다.
- [ ] 할일 2 : 여러 모델로 전이학습된 프로토타입 모델을 훈련시켜본다.
                   ( 정석 : Xception, 한결 : MobileNetV2, 혜영 : EfficientNet, 정아 : ReNet) 
- [ ] 할일 3 : 훈련하는 데 걸리는 시간, 평가지표 등을 기록해두고 실제 훈련시 사용할 데이터셋의 크기와 하이퍼파라미터등에 대해 논의한다.
